const navGlider=document.createElement('span');
navGlider.className='nav-glider';navGlider.setAttribute('aria-hidden','true');movingNav.prepend(navGlider);
function moveGlider(){const a=movingNav.querySelector('a.active');navGlider.style.opacity=a?'1':'0';if(a){navGlider.style.width=a.offsetWidth+'px';navGlider.style.transform=`translateX(${a.offsetLeft}px)`;}}
const sections=[...document.querySelectorAll('main>section[id]')];
let activeFrame=0;
function updateActive(){activeFrame=0;let id='';const line=window.innerHeight*.3;for(const s of sections){if(s.getBoundingClientRect().top<=line)id=s.id;}if(window.innerHeight+window.scrollY>=document.documentElement.scrollHeight-3)id='our-dataset';if(id==='quantitative')id='results';movingNav.querySelectorAll('a').forEach(a=>{const on=a.hash==='#'+id;a.classList.toggle('active',on);if(on)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});moveGlider();}
window.addEventListener('scroll',()=>{if(!activeFrame)activeFrame=requestAnimationFrame(updateActive);},{passive:true});window.addEventListener('resize',updateActive);new ResizeObserver(moveGlider).observe(movingNav);updateActive();
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.remove('reveal-pending');revealObserver.unobserve(entry.target);}}),{threshold:.04});
if(!reducedMotion.matches)document.querySelectorAll('.section>.section-heading,.outputs article,.steps article').forEach(el=>{if(el.getBoundingClientRect().top>innerHeight){el.classList.add('reveal-ready','reveal-pending');revealObserver.observe(el);}});
reducedMotion.addEventListener('change',()=>{if(reducedMotion.matches)document.querySelectorAll('.reveal-pending').forEach(el=>el.classList.remove('reveal-pending'));});
let sceneRequest=0;
document.querySelectorAll('[data-scene]').forEach(button=>button.addEventListener('click',async()=>{const request=++sceneRequest,scene=scenes[button.dataset.scene],img=document.querySelector('#scene-image'),frame=img.closest('figure');const preload=new Image();preload.src='assets/'+scene.file;frame.setAttribute('aria-busy','true');frame.classList.add('scene-loading');try{await preload.decode();if(request!==sceneRequest)return;img.src=preload.src;img.alt=scene.alt;document.querySelector('#scene-caption').textContent=scene.caption;document.querySelectorAll('[data-scene]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button));});}catch{if(request===sceneRequest)document.querySelector('#scene-caption').textContent='Unable to load this image. Please try again.';}finally{if(request===sceneRequest){frame.classList.remove('scene-loading');frame.removeAttribute('aria-busy');}}}));
const imageViewport=document.querySelector('.dialog-image'),fitButton=document.querySelector('#zoom-fit'),originalButton=document.querySelector('#zoom-original');
function setZoom(original){imageViewport.classList.toggle('original',original);fitButton.setAttribute('aria-pressed',String(!original));originalButton.setAttribute('aria-pressed',String(original));imageViewport.scrollTop=0;imageViewport.scrollLeft=0;}
fitButton.addEventListener('click',()=>setZoom(false));originalButton.addEventListener('click',()=>setZoom(true));
let zoomOpener;
document.querySelectorAll('[data-zoom]').forEach(button=>button.addEventListener('click',()=>{zoomOpener=button;const src=button.querySelector('img'),target=document.querySelector('#zoom-image');target.src=src.src;target.alt=src.alt;document.querySelector('#zoom-caption').textContent=button.closest('figure').querySelector('figcaption').textContent;setZoom(false);dialog.showModal();document.body.classList.add('modal-open');document.querySelector('#close-lightbox').focus();}));
document.querySelector('#close-lightbox').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');zoomOpener?.focus({preventScroll:true});});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
